version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn run build

      - run: mv public zq-blog

      - persist_to_workspace:
          root: ~/repo
          paths:
            - zq-blog
  deploy:
    machine:
      enabled: true
    steps:
#      - run: sudo apt-get update && sudo apt-get install rsync
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - '44:a6:c2:48:08:33:1e:1a:3d:95:92:23:ae:51:af:24'
            - 'd7:97:6e:94:6a:9d:7e:d2:d9:bd:93:ba:48:e4:20:7a'
      - run: cd ~/repo/zq-blog && ls
      - run: ip addr show
      - run: ping -c 5 47.52.171.93
#      - run: ssh -v root@47.52.171.93
      - run: echo "ggggg" | ssh -v root@120.26.82.73 "cat > output.txt"
      - run: echo "ggggg" | ssh -v root@47.52.171.93 "cat > output.txt"
      - run:
          name: Deploy Over SSH
          command: |
            rsync -va --delete ~/repo/zq-blog/ $BEAF_USER@$BEAF_HOST:/usr/web/zq-blog/deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
