version: 2

executors:
  my-executor:
    docker:
      - image: circleci/node
    working_directory: /tmp

jobs:
  build:
    executor: my-executor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn run build

      - persist_to_workspace:
          root: public
          paths:
            - *

  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/public
      - add_ssh_keys:
          fingerprints:
           - "d7:97:6e:94:6a:9d:7e:d2:d9:bd:93:ba:48:e4:20:7a"
      - run: ls
      - run:
          name: Deploy Over SSH
          command: |
            ssh $BEAF_USER@$BEAF_HOST "cd .. && ls"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

